sudo: required

language: python

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  docker build -t arpeggio .

script:
  - docker run --rm -it arpeggio python arpeggio.py -h
